name: Push Docker Images

on:
  push:
    branches:  # Run the workflow for every push in master branch
      - 'master'

jobs:
  push:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    strategy:
      matrix:
        services: ['udagram-api-feed', 'udagram-api-user', 'udagram-frontend', 'reverseproxy']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push docker image
        run : |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          docker build -t ${{ matrix.services }} ./${{ matrix.services }}
          docker tag ${{ matrix.services }} meharusama/${{ matrix.services }}:$GITHUB_SHA
          docker push meharusama/${{ matrix.services }}:$GITHUB_SHA

      - name: Success Message
        run: echo "Docker Image for service ${{ matrix.services }} built and pushed successfully"
